-- 코드를 입력하세요
SELECT B.BOARD_ID, REPLY_ID, R.CONTENTS, R.CREATED_DATE
from USED_GOODS_BOARD AS B 
INNER JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE LIKE %"10"% #AND R.CREATED_DATE LIKE %"10"%